### ISSUE TITLE
thingiverse cannot be downloaded

### ISSUE THREAD

**Issue by JunzheJosephZhu** [allenai/objaverse-xl#22]
![image](https://github.com/allenai/objaverse-xl/assets/24391451/c1ad2eb8-bc13-4501-b1db-b142cdbc57a1)
![image](https://github.com/allenai/objaverse-xl/assets/24391451/aad5f832-b6c3-4bb8-9966-4a4196d920e1)
I tried both on school server and my PC. In both cases, tree ~/.objaverse shows only thingiverse.parquet under thingiverse folder
![image](https://github.com/allenai/objaverse-xl/assets/24391451/1cfc8b1f-6815-4980-a7e3-e94be4338a69)

**Comment by JunzheJosephZhu** [comment]
I pasted the link into browser and it downloads. Wget downloads as well. On the colab notebook it works as well, but not on both my PC and school server.

**Comment by JunzheJosephZhu** [comment]
Found the solve:
Need to add:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
and in thingiverse.py, change to response.get(url, headers=headers, stream=True)
Can someone update this repo?

**Comment by ouceduxzk** [comment]
the website currently added a redirection with a js file , so naively request with that url will not work any more.

**Comment by bc129697** [comment]
> stream=True

hello，are you slolve this problem?

**Comment by GostInShell** [comment]
This works for me. Simlar to @JunzheJosephZhu 's solution.
```
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0'}
with open(temp_path_tmp, "wb") as file:
req = urllib.request.Request(url=hf_url, headers=headers)
with urllib.request.urlopen(req) as response:
    file.write(response.read())
```
